#!/usr/bin/env python2.7

import nflgame

# All we really have to do is load up all of the Game objects. The JSON will
# be automatically cached for us.
nflgame.games(2009, preseason=True)
nflgame.games(2009, preseason=False)
nflgame.games(2010, preseason=True)
nflgame.games(2010, preseason=False)
nflgame.games(2011, preseason=True)
nflgame.games(2011, preseason=False)
nflgame.games(2012, preseason=True)
# nflgame.games(2012, preseason=False) 

