#!/usr/bin/env python2.7

import csv
import sys

import nflgame
import nflgame.stats as stats

examples = []
def exists(statid):
    for info in examples:
        if info['statid'] == statid:
            return True
    return False

# games = nflgame.games(2011, week=[1, 2, 3, 4, 5]) 
# games = nflgame.games(2011) 
games = nflgame.games(2009) + nflgame.games(2010) \
        + nflgame.games(2011) + nflgame.games(2012, preseason=True)
for g in games:
    driveNums = []
    for driveNum in g.data['drives']:
        try:
            driveNums.append(int(driveNum))
        except:
            pass
    for driveNum in sorted(driveNums):
        drive = g.data['drives'][str(driveNum)]
        for playid in sorted(drive['plays'], key=int):
            play = drive['plays'][str(playid)]
            for playerid, player_plays in play['players'].iteritems():
                for player_play in player_plays:
                    sid = int(player_play['statId'])
                    info = {
                        'statid': sid,
                        'eid': g.eid,
                        'posteam': play['posteam'],
                        'drive': driveNum,
                        'playid': playid,
                        'down': int(play['down']),
                        'ydstogo': int(play['ydstogo']),
                        'ydsnet': int(play['ydsnet']),
                        'team': player_play['clubcode'],
                        'name': player_play['playerName'],
                        'yards': int(player_play['yards']),
                        'qtr': int(play['qtr']),
                        'time': play['time'],
                        'note': play['note'],
                        'desc': play['desc'],
                    }
                    # if not exists(info['statid']): 
                    cat = stats.categories[info['statid']]
                    if cat['field'] is None and cat['cat'] == 'team':
                        examples.append(info)
                    # if sid not in stats.categories and sid not in examples: 
                        # examples[info['statid']] = info 

fields = ['statid', 'eid', 'posteam', 'drive', 'playid',
          'down', 'ydstogo', 'ydsnet', 'team',
          'name', 'yards', 'qtr', 'time', 'note', 'desc']
w = csv.DictWriter(sys.stdout, fieldnames=fields)
w.writerow({k:k for k in fields})
w.writerows(sorted(examples, key=lambda info: info['statid']))
# for statid in sorted(examples): 
# for statid in examples: 
    # w.writerow(examples[statid]) 

